- type: job
  id: ESCaptain
  name: ESjob-name-captain
  description: ESjob-description-captain
  playTimeTracker: ESJobCaptain
  weight: 20 # The only guy with a higher weight, he is picked first for objective protection reasons.
  startingGear: ESCaptainGear
  icon: "JobIconCaptain"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: ESCaptainGear
  equipment:
    shoes: ClothingShoesColorBrown
    eyes: ClothingEyesGlassesSecurity
    id: CaptainPDA
    gloves: ClothingHandsGlovesCaptain
    ears: ClothingHeadsetAltCommand
    head: ClothingHeadHatCaptain
    jumpsuit: ClothingUniformJumpsuitCaptain
    outerClothing: ClothingOuterArmorCaptainCarapace
    back: ClothingBackpackCaptain
  storage:
    back:
    - ESBoxSurvival
    - Flash

- type: chameleonOutfit
  id: ESCaptain
  job: ESCaptain
  hidden: false
