- type: job
  id: ESHeadOfPersonnel
  name: ESjob-name-hop
  description: ESjob-description-hop
  playTimeTracker: ESJobHeadOfPersonnel
  startingGear: ESHoPGear
  icon: "JobIconHeadOfPersonnel"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Cryogenics
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Lawyer
  - Cargo
  - Atmospherics
  - Medical
  - GenpopEnter
  - GenpopLeave
  # Effectively all access minus Captain, Head of Security, and Armory as of 23/12/25
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: ESHoPGear
  equipment:
    shoes: ClothingShoesColorBrown
    eyes: ClothingEyesHudSecurity
    id: HoPPDA
    ears: ClothingHeadsetAltCommand
    head: ClothingHeadHatHopcap
    belt: BoxFolderClipboardThreePapers
    jumpsuit: ClothingUniformJumpsuitHoP
    back: ClothingBackpack
  storage:
    back:
    - ESBoxSurvival
    - Flash
