- type: job
  id: ESAssistant
  name: ESjob-name-assistant
  description: ESjob-description-assistant
  playTimeTracker: ESJobAssistant
  weight: -99999 # pick these guys last we don't need more of them.
  startingGear: ESAssistantGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  access:
  - Maintenance

- type: startingGear
  id: ESAssistantGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: PassengerPDA
    ears: ClothingHeadsetGrey
    jumpsuit: ClothingUniformJumpsuitColorGrey
    back: ClothingBackpack
  storage:
    back:
    - ESBoxSurvival
