- type: job
  id: ESClown
  name: ESjob-name-clown
  description: ESjob-description-clown
  playTimeTracker: ESJobClown
  startingGear: ESClownGear
  icon: "JobIconClown"
  supervisors: job-supervisors-hop
  access:
  - Theatre
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: Clumsy
      gunShootFailDamage:
        types: #literally just picked semi random valus. i tested this once and tweaked it.
          Blunt: 5
          Piercing: 4
          Heat: 3
      catchingFailDamage:
        types:
          Blunt: 1
    - type: SleepEmitSound
      snore: /Audio/Voice/Misc/silly_snore.ogg
      interval: 10
  - !type:AddImplantSpecial
    implants: [ SadTromboneImplant ]

- type: startingGear
  id: ESClownGear
  equipment:
    shoes: ClothingShoesClown
    mask: ClothingMaskClown
    id: ClownPDA
    ears: ClothingHeadsetService
    jumpsuit: ClothingUniformJumpsuitClown
    back: ClothingBackpackClown
    pocket1: BikeHorn
    pocket2: ClownRecorder
  storage:
    back:
    - ESBoxHug
    - RubberStampClown
    - CrayonRainbow

- type: chameleonOutfit
  id: ESClown
  job: ESClown
  hidden: false
