- type: job
  id: ESReporter
  name: ESjob-name-reporter
  description: ESjob-description-reporter
  playTimeTracker: ESJobReporter
  startingGear: ESReporterGear
  icon: "JobIconReporter"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance

- type: startingGear
  id: ESReporterGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: ReporterPDA
    ears: ClothingHeadsetService
    head: ClothingHeadHatFedoraGrey
    jumpsuit: ClothingUniformJumpsuitReporter
    back: ClothingBackpack
  storage:
    back:
    - ESBoxSurvival

- type: chameleonOutfit
  id: ESReporter
  job: ESReporter
  hidden: false
